services:
    app:
        build:
            context: ..
            dockerfile: docker/Dockerfile

    webserver:
        image: nginx:${NGINX_VERSION}
        environment:
            SERVER_NAME: ${SERVER_NAME}
        ports:
            - ${SERVER_PORT}:80
        volumes:
            - ./config/nginx/default.conf.template:/etc/nginx/templates/default.conf.template
        depends_on:
            - app
