# docker compose -f docker/docker-compose.prod.yaml --env-file .env --env-file .env.prod.local -p stats-prod up -d

include:
    - docker-compose.base.yaml

services:
    app:
        build:
            target: prod
        volumes:
            - app-code:/var/www

    webserver:
        volumes:
            - app-code:/var/www

volumes:
    app-code:
        name: stats-prod_app-code
